var players = [
{ name: "Anna" , score: 100 , bets: { reddice : 5 } , cost: 1 } ,
{ name: "Ben" ,  score: 100 , bets: { reddice : 3 , calendar : "Aug 1" } , cost: 2 }
]
theDatas=["Timestamp","Username","Total score","Red dice","Red dice [Score]","Red dice [Feedback]","Total of white dice","Total of white dice [Score]","Total of white dice [Feedback]","Order of {A,B,C}","Order of {A,B,C} [Score]","Order of {A,B,C} [Feedback]","Both white dice (order doesn't matter) e.g. 3,5","Both white dice (order doesn't matter) e.g. 3,5 [Score]","Both white dice (order doesn't matter) e.g. 3,5 [Feedback]","Total of all four dice","Total of all four dice [Score]","Total of all four dice [Feedback]","Calendar month","Calendar month [Score]","Calendar month [Feedback]","Order of {W,X,Y,Z} e.g. WYZX","Order of {W,X,Y,Z} e.g. WYZX [Score]","Order of {W,X,Y,Z} e.g. WYZX [Feedback]","Mystery letter or number","Mystery letter or number [Score]","Mystery letter or number [Feedback]","Day of the month","Day of the month [Score]","Day of the month [Feedback]","Red die, white dice, black die: e.g.: 4,(5,2),6","Red die, white dice, black die: e.g.: 4,(5,2),6 [Score]","Red die, white dice, black die: e.g.: 4,(5,2),6 [Feedback]","Full date (e.g. August 14)","Full date (e.g. August 14) [Score]","Full date (e.g. August 14) [Feedback]","Order of both letter sets, e.g. CBA,WZYX","Order of both letter sets, e.g. CBA,WZYX [Score]","Order of both letter sets, e.g. CBA,WZYX [Feedback]"
,"2019/08/14 10:49:20 am GMT+10","tso0005@uysc.vic.edu.au","0.00 / 0","3","-- / 0","","7","-- / 0","","A,C,B","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0",""
,"2019/08/14 10:49:38 am GMT+10","oco0002@uysc.vic.edu.au","0.00 / 0","3","-- / 0","","6 ","-- / 0","","B,C,A","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0",""
,"2019/08/14 10:50:05 am GMT+10","vog0005@uysc.vic.edu.au","0.00 / 0","3","-- / 0","","6","-- / 0","","B,C,A","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0",""
,"2019/08/14 10:50:22 am GMT+10","wat0020@uysc.vic.edu.au","0.00 / 0","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","October","-- / 0","","","-- / 0","","C","-- / 0","","27","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0",""
,"2019/08/14 10:50:51 am GMT+10","osh0003@uysc.vic.edu.au","0.00 / 0","1","-- / 0","","2","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0",""
,"2019/08/14 10:52:45 am GMT+10","nis0003@uysc.vic.edu.au","0.00 / 0","4","-- / 0","","10","-- / 0","","C,A,B","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0","","","-- / 0",""
] ;
